import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body lang="fa" className="flex flex-wrap w-full h-full">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Navbar />
          <main className="flex w-full pt-[60px] md:pt-[70px]">{children}</main>
          <Footer />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
